"""Visual design tokens and icon sets used by the desktop UI."""

COLORS = {
    "bg_primary": "#08080d",
    "bg_secondary": "#101019",
    "bg_card": "#171723",
    "bg_card_hover": "#1f1f2e",
    "bg_card_active": "#262638",
    "glass": "#15151f",
    "glass_hover": "#1d1d2b",
    "glass_elevated": "#1c1c2a",
    "accent": "#00d9a5",
    "accent_hover": "#00f0b5",
    "accent_dim": "#00a37d",
    "accent_glow": "#0f453f",
    "accent_secondary": "#00b4d8",
    "danger": "#ff4757",
    "danger_hover": "#ff6b7a",
    "danger_glow": "#4f212d",
    "warning": "#ffb347",
    "warning_hover": "#ffc570",
    "info": "#3498db",
    "info_hover": "#5dade2",
    "success": "#00e676",
    "success_hover": "#69f0ae",
    "text_primary": "#ffffff",
    "text_secondary": "#b0b0c0",
    "text_muted": "#6b6b80",
    "border": "#26263a",
    "border_hover": "#3d3d5c",
    "border_accent": "#0f453f",
    "gradient_start": "#00d9a5",
    "gradient_end": "#00b4d8",
    "track_strip": "#00d9a5",
}

RADIUS = {
    "sm": 8,
    "md": 12,
    "lg": 16,
    "xl": 20,
    "pill": 24,
    "bar": 6,
}

PAD = {
    "xs": 4,
    "sm": 8,
    "md": 12,
    "lg": 16,
    "xl": 20,
    "xxl": 24,
}

ICONS_STD = {
    "logo": "◉",
    "music": "♪",
    "url": "∘",
    "preview": "☰",
    "settings": "⚙",
    "folder": "▣",
    "log": "≡",
    "paste": "⎘",
    "clear": "✕",
    "download": "↓",
    "cancel": "✕",
    "success": "✓",
    "error": "✗",
    "warning": "⚠",
    "info": "ℹ",
    "ready": "●",
    "downloading": "↓",
    "playlist": "☰",
    "retry": "↻",
    "pause": "⏸",
}

ICONS_NERD = {
    "logo": "\uf001",
    "music": "\uf001",
    "url": "\uf0c1",
    "preview": "\uf03a",
    "settings": "\uf013",
    "folder": "\uf07b",
    "log": "\uf15c",
    "paste": "\uf0ea",
    "clear": "\uf00d",
    "download": "\uf019",
    "cancel": "\uf00d",
    "success": "\uf00c",
    "error": "\uf00d",
    "warning": "\uf071",
    "info": "\uf129",
    "ready": "\uf111",
    "downloading": "\uf019",
    "playlist": "\uf03a",
    "retry": "\uf01e",
    "pause": "\uf04c",
}
